sonar.projectVersion=1.0.0
sonar.sourceEncoding=UTF-8
sonar.coverage.exclusions=**
sonar.sources=src,pages,iframe
sonar.exclusions=**/node_modules/**, **/.next/**, **/public/**
sonar.javascript.jsconfig.path=jsconfig.json